### ISSUE TITLE
Remove all Python2 dependencies and transition to Python3 completely

### ISSUE THREAD

**Issue by randybias** [OpenSDN-io/community#25]

**Comment by randybias** [comment]
@Andrey-mp how do we know when this is 100% complete?

**Comment by Andrey-mp** [comment]
- moved to python3 all components which are not related to cassandra
- switched default from thrift to CQL
- removed pycassa/thrift libraries from build process

next step is to try to switch python definition to python globally and try to build. otherwise - switch it one by one for all components.
@qblivion is working on it.

**Comment by randybias** [comment]
Where are we at?

**Comment by Andrey-mp** [comment]
@qblivion please provide current status.

**Comment by qblivion** [comment]
Greetings Randy @randybias,

Currently, we have two main tasks: updating the analytics package and codebase to Python 3 and migrating the config package to Python 3. Once these tasks are completed, we will be able to drop Python 2 for the entire project.

Right now, I am working on supporting the net-snmp package in the analytics-snmp-collector and refactoring the analytics Python code. I estimate this will take about a week, after which we can finalize the deprecation of Python 2 for the entire project.

**Comment by randybias** [comment]
Status?

**Comment by qblivion** [comment]
Hello!

I have finished working on the analytics module. It took more time than I anticipated because of the net-snmp package, but it now works correctly with Python 3. I have two parts left: the kubemanager and config packages. The kubemanager is almost done, and I expect the config package to be more challenging. I will keep you updated.

**Comment by randybias** [comment]
Any ETA?

**Comment by Andrey-mp** [comment]
I would say - a week since now to switch to python3.
and then ensure that python2 is not used - one more week

**Comment by randybias** [comment]
Updates?

**Comment by qblivion** [comment]
Ready to merge. All packages should now work on Python 3. We are removing Python 2 dependencies.

**Comment by Andrey-mp** [comment]
all deps are removed in release 1.
next work will be done in https://github.com/OpenSDN-io/community/issues/63
